### PR TITLE
Test on php 7.3

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by joelwurtz** [comment]
From what i have seen it seems that `stream_set_chunk_size` does not work like before in php 7.2. Don't know what change but this is only explanation possible.

**Comment by joelwurtz** [comment]
Ok, after some search it's coming from fread which now better respect length pass to it #110 should fix those tests

**Comment by dbu** [comment]
can you please rebase on master now that the chunk issue should be fixed?

**Comment by joelwurtz** [comment]
I think tests are played on the merged version and since there are green we can safely merge this ?

**Comment by dbu** [comment]
thanks. indeed, restarting the tests was enough.

**Pull request merged**
