### PR TITLE
Improve package

### PR DESCRIPTION
**Pull request by sagikazarmark**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

#### What's in this PR?

Improve some package files.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@php-http/owners any idea why StyleCI suddenly gone mad?

/cc @grahamcampbell

**Comment by GrahamCampbell** [comment]
StyleCI is doing one build for a PR, and one for a push, exactly like Travis does.

See https://blog.alt-three.com/new-pr-analysis-system/ for more details.

**Comment by sagikazarmark** [comment]
@GrahamCampbell analysis was okay until yesterday, now it wants to remove trailing period from docblocks: https://styleci.io/repos/48317882

**Comment by GrahamCampbell** [comment]
Ah, right. That's a change to the symfony CS. They made this change in their codebase very recently, and our rules have been updated accordingly.

**Comment by GrahamCampbell** [comment]
I actually forgot to regen our docs website after the last deploy. I'll do that now!

**Comment by sagikazarmark** [comment]
Do you have a PR/link where they introduced this change? Just for reference in our boilerplate and I would like to see some reasoning too if any. Thanks.

**Comment by GrahamCampbell** [comment]
Of course. Here you are: https://github.com/symfony/symfony/pull/19198.

**Comment by GrahamCampbell** [comment]
That said, it does look like they specifically are only removing the dots from param and return annotations. I will look into this.

**Comment by sagikazarmark** [comment]
Thanks for the quick response.

**Pull request merged**
