### PR TITLE
Enhancement: Normalize composer.json

### PR DESCRIPTION
**Pull request by localheinz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | n/a
| Documentation   | n/a
| License         | MIT

#### What's in this PR?

This PR

* [x] requires `localheinz/composer-normalize` as development dependency
* [x] runs `composer validate` and `composer normalize --dry-run` on Travis
* [x] normalizes `composer.json`

💁‍♂️ For reference, see https://github.com/localheinz/composer-normalize.

### CODE REVIEW

**Comment by localheinz** [comment]
@dbu 

I have made a few changes, thank you for suggesting to use `localheinz/composer-normalize` in the build pipeline!

**Comment by localheinz** [comment]
Hmm, Scrutinizer currently fails, see https://scrutinizer-ci.com/g/php-http/message/inspections/3d11bd3a-d6fc-459b-bdf4-1507e4c752ae:

Screen Shot 2019-08-03 at 20 07 40

**Comment by dbu** [comment]
does that mean that scrutinizer is using an outdated version of composer? can you check with the scrutinizer people? that said, i personally don't look at the scrutinizer output much - we could also drop it imho.

**Comment by localheinz** [comment]
Thank you, @dbu!

**Pull request merged**
